 
// the configured options and settings for dngconvert
#define DNGCONVERT_VERSION_MAJOR @DNGCONVERT_VERSION_MAJOR@
#define DNGCONVERT_VERSION_MINOR @DNGCONVERT_VERSION_MINOR@
#define DNGCONVERT_VERSION_PATCH @DNGCONVERT_VERSION_PATCH@

#define DNGCONVERT_VERSION_MAKE(a,b,c) #a"."#b"."#c
#define _DNGCONVERT_VERSION_MAKE(a,b,c) DNGCONVERT_VERSION_MAKE(a,b,c)
#define DNGCONVERT_VERSION_STR _DNGCONVERT_VERSION_MAKE(DNGCONVERT_VERSION_MAJOR,DNGCONVERT_VERSION_MINOR,DNGCONVERT_VERSION_PATCH)
